-- BUSCAR POR PRODUTO DENTRO DA VENDA
-- QUERY -- SELECT

SELECT PRECO_PRODUTO FROM PRODUTO WHERE ID_PRODUTO = 1;

SELECT PRECO_UNITARIO FROM ITEM_VENDA WHERE ID_VENDA = 2;

SELECT ID_PRODUTO, PRECO_UNITARIO FROM ITEM_VENDA WHERE ID_VENDA = 1 AND ID_PRODUTO = 1;
-- PESQUISANDO POR NOME 
SELECT IV.PRECO_UNITARIO, P.NOME_PRODUTO
FROM ITEM_VENDA AS IV -- AS = APELIDO
JOIN PRODUTO AS P  ON IV.ID_PRODUTO = P.ID_PRODUTO -- JUNTAR
WHERE IV.ID_VENDA = 1 AND P.NOME_PRODUTO LIKE '%CAFE%';

-- BUSCANDO TODAS AS VENDAS DE UM CLIENTE
SELECT *
FROM VENDA
WHERE ID_CLIENTE_VENDA = 1;

-- BUSCAR PRODUTO MAIS VENDIDO
SELECT P.NOME_PRODUTO, SUM(iv.QUANTIDADE_ITEM) AS TOTAL_VENDIDO
FROM ITEM_VENDA AS iv
JOIN PRODUTO P ON P.ID_PRODUTO = iv.ID_PRODUTO
GROUP BY P.NOME_PRODUTO;